// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  trackerSidebar: [{ type: 'autogenerated', dirName: 'tracker' }],

  inventorySidebar: [
    {
      type: 'category',
      label: 'Inventory and Subscription', 
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'Inventory and Subscription' }, 
      ],
    },
  ],

  epmsSidebar: [{ type: 'autogenerated', dirName: 'epms' }],
  starlinkSidebar: [{ type: 'autogenerated', dirName: 'starlink' }],
  workflowSidebar: [{ type: 'autogenerated', dirName: 'workflow' }],
  adminSidebar: [{ type: 'autogenerated', dirName: 'admin-ops' }],
};

export default sidebars;
